### ISSUE TITLE
detect_noisy_strips function

### ISSUE THREAD

**Issue by dieggo111** [Chilldose/Alibava_analysis#7]
Bondet ihr beide beetle chips an? Also komplett 256 channels? Wir machen das nicht. I.d.R. noch nicht mal komplett 128 channels sondern vll 30 - 60 streifen oder so. Dann würde mich interessieren, wie sich die ungebondeten channels verhalten? Werden die hier auch rausgefischt oder gibt das vll komische artefakte? 

Im allgemeinen wäre das ein guter zusätzlicher Parameter (welcher beetle chip angebondet war, 0 oder 1), weil man sich so nur die Hälfte der channels auswerten muss. Das gibts noch nicht in der config file.

**Comment by Chilldose** [comment]
Wir bonden immer alle channels an. Und wir versuchen immer alle 256 zu bonden, so das nichts offen bleibt. 
Nichts desto trotz sind bei einem Baby sensor ca 20 streifen nicht gebondet worden weil ein Fehler gemacht wurde. Diese channels Zeigen immer recht großes Noise was die funktion recht leicht erkennt. Für weitere Streifen kann man manual masken im config. 

Das es noch nicht geht das man einen chip alleine voll masked ist noch ein feature das rein gehört. Das habe ich damals nicht bedacht und ist mir erst vor kurzem aufgefallen, dass es noch rein gehört.
