### ISSUE TITLE
import_h5 vs read_binary_alibava

### ISSUE THREAD

**Issue by dieggo111** [Chilldose/Alibava_analysis#8]
Wie schon angemerkt returnt import_h5 ne liste mit hdf5 objeckten/dicts und read_binary ein dict. Du willst offensichtlich die möglichkeit haben, verschiedene messfiles (ich nehme an für verschiedene spannungen) durchlaufen zu lassen und dafür immer die gleichen calibration und pedestal auswertugnen zu nehmen. Richtig? Dazu hab ich 2 anmerkungen:
1) Hast du mal die Abweichungen zwischen den Spannungen für pedestal und calibration gecheckt? Wir machen halt für jeden messung eine calib und einen pedestal durchlauf, also hat auch jede messfile eine calib und eine ped file. Vll ist das ja auch unnötig. Ich hab das noch nie in frage gestellt. Müsste man mal checken. 
2) Unabhängig von der physikalischen bewertung, sollte man das im code bsichen ändern. beide funktionen sollten nur auf einen pfad angewendet werden und dann das gleiche returnen (einen dict). Ich würde dann in deiner main file eine funtion einführen, die eine liste mit pfaden aus der config rauszieht und diese dann in der main durchschleifen. So machts für mich mehr sinn. So kann man auch (nach unserer methode) calib und pedestals durchiterieren ohne in der klasse was zu ändern.

**Comment by Chilldose** [comment]
Zu 1: Ja du hast vollkommen recht. Es gibt ziemlich sicher einen Unterschied in der Kalibrierung. Das habe ich mal gesehen wie ich vergessen habe zu biasen beim kalibrieren. Wie hoch dieser aber jenseits von z.B 100 V ist weiß ich nicht.

Zu 2: Ich habe es mir jetzt nochmals angeschaut. Du hast recht. Machen wir es so wie du sagst.

**Comment by dieggo111** [comment]
Hey Dominic, der beta branch läuft bei mir auch einwandfrei. Ich würde jetzt vor allem obiges issue mal angehen. Also dass die analyse jeweils ein pedestal, calibration und messfile durchnudelt. Die Schleife (falls man mehrere Messungen mit den jeweiligen Calibs und Pedestals analysieren möchte) würd ich in die main packen. Da ist sie am besten aufgehoben. Wär das OK für dich?

**Comment by Chilldose** [comment]
Ich habe mir das nochmals angeschaut. Die Schleife über mehrere Messfiles in der Analyse macht dort schon Sinn. Weil geplant ist automatische CCE Plots zu generieren. Hierzu muss die Analyse aber alles wissen über jeden schritt und file. Das du das aber in die Main auslagern willst, stellt hier aber keine Hürde da. Du kannst dann halt beides machen. Entweder ein messfiles nach dem andern aus der Config, (es ist ja nur ein dict wo ein eintrag geänder wird, oder wenn du CCE haben willst mit mehreren Files.

Edit: Im Prinzip musst du nur nach dem if in zeiler 36 eine Schleife über alle Files machen und halt einen path nach dem andern an die MainLoop füttern.

**Comment by dieggo111** [comment]
Ich hab mich glaub nicht klar ausgedrückt: Ich möchte dass die Analyse ein komplettes Datenset analysiert (Pedestal, Calibration und Messfile). Bisher kann man ein Pedestal und eine Cali file angeben, aber mehrere Messfiles. D.h. für alle Messfiles wird die gleichen Kalibrations- und Pedestalwerte benutzt. Sollte nicht so sein, wie oben diskutiert. Im Zuge dessen bin ich grad noch bei ein paar anderen Änderungen dran. 
1) Plotfunktionen auslagern
2) Neue Plots hinzufügen/ändern für Calibration
3) Paar Kommentare ändern/hinzufügen (so dass ichs besser verstehe)
Das sind die Änderungen die ich grad vornehme. Also nichts wildes.

**Comment by Chilldose** [comment]
Aso , jetzt bin ich bei dir.

Ja mach mal und mach dann ein pull request.
