### ISSUE TITLE
noise_calc vs. nb_noise_calc

### ISSUE THREAD

**Issue by dieggo111** [Chilldose/Alibava_analysis#9]
Dieser Trick mit np.subtract die arrays direkt anstatt durch die events zu loopen und die events einzeln zu bearbeiten ist halt mega effizient. Hab hier bei mir ca 8 sec vs. 1 sec. Warum gibt's denn überhaupt die option das verfahren auszuwählen? In dem Fall ist ja gar kein numba involviert... kann man sich doch sparen oder?

**Comment by Chilldose** [comment]
Es ist noch eine Legacy weil ursprünglich wollte ich es so einfach wie möglich machen um logik fehler zu finden. Bei np.subtract ist es noch leicht zu verstehen. Wenn man aber nd.array Operationen über verschiedene Achsen macht ist das ganze nicht mehr so einfach zu verstehen. Am Anfang habe ich mir gedacht das numba das ausgleicht. Da dort alles in c übersetzt wird. Später wurde mir erst bewusst das alles in ufuncts von numpy zu packen. Jedoch gibt es hier auch die möglichkeit numba über numpy funktionen zu packen. Damit kann man dann nochmal schneller werden. Das ist aber wie du siehst noch nicht drin.
